### ISSUE TITLE
settings for this extension cannot be displaed

### ISSUE THREAD

**Issue by tuxedotje** [konkor/you2ber#18]
Stack trace:
  _init@/home/jaap/.local/share/gnome-shell/extensions/you2ber@konkor/prefs.js:110:10
  wrapper@resource:///org/gnome/gjs/modules/script/_legacy.js:83:27
  _init@/home/jaap/.local/share/gnome-shell/extensions/you2ber@konkor/prefs.js:73:20
  wrapper@resource:///org/gnome/gjs/modules/script/_legacy.js:83:27
  _Base.prototype._construct@resource:///org/gnome/gjs/modules/script/_legacy.js:19:10
  newClass@resource:///org/gnome/gjs/modules/script/_legacy.js:115:21
  buildPrefsWidget@/home/jaap/.local/share/gnome-shell/extensions/you2ber@konkor/prefs.js:258:16
  _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:209:40
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
  run@resource:///org/gnome/gjs/modules/script/package.js:206:19
  start@resource:///org/gnome/gjs/modules/script/package.js:190:8
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17

**Comment by konkor** [comment]
Yeah. You can run the preferences window from the GUI so. I should disable it in a browser...
Thanks!

**Comment by woebau** [comment]
Hi, I see the exact same error as @tuxedotje #with an additional line above it: "TypeError: this.add is not a function". This appears when settings are called from the browser as well as from gnome extensions. When I click on the icon in the top bar, the "preferences" open with General - Audio - Video - Subtitles, but nothing else.
I am working on stock Pop_OS 21.10. Thank you in advance and keep up your good work! Michael
